In [1]:
import pandas as pd; import numpy as np; import matplotlib.pyplot as plt; import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error

In [10]:
df = pd.read_excel('/content/sample_data/Graded-assessment-College.xlsx')
df.head()

                     Unnamed: 0 Private  Apps  ...  perc.alumni  Expend  Grad.Rate
0  Abilene Christian University     Yes  1660  ...           12    7041         60
1            Adelphi University     Yes  2186  ...           16   10527         56
2                Adrian College     Yes  1428  ...           30    8735         54
3           Agnes Scott College     Yes   417  ...           37   19016         59
4     Alaska Pacific University     Yes   193  ...            2   10922         15

[5 rows x 19 columns]

In [11]:
# drop 0 column
df.drop(columns=['Unnamed: 0'], inplace=True)
df.head()

  Private  Apps  Accept  Enroll  ...  S.F.Ratio  perc.alumni  Expend  Grad.Rate
0     Yes  1660    1232     721  ...       18.1           12    7041         60
1     Yes  2186    1924     512  ...       12.2           16   10527         56
2     Yes  1428    1097     336  ...       12.9           30    8735         54
3     Yes   417     349     137  ...        7.7           37   19016         59
4     Yes   193     146      55  ...       11.9            2   10922         15

[5 rows x 18 columns]

In [12]:
df.describe().round(2)

           Apps    Accept   Enroll  ...  perc.alumni    Expend  Grad.Rate
count    777.00    777.00   777.00  ...       777.00    777.00     777.00
mean    3001.64   2018.80   779.97  ...        22.74   9660.17      65.46
std     3870.20   2451.11   929.18  ...        12.39   5221.77      17.18
min       81.00     72.00    35.00  ...         0.00   3186.00      10.00
25%      776.00    604.00   242.00  ...        13.00   6751.00      53.00
50%     1558.00   1110.00   434.00  ...        21.00   8377.00      65.00
75%     3624.00   2424.00   902.00  ...        31.00  10830.00      78.00
max    48094.00  26330.00  6392.00  ...        64.00  56233.00     118.00

[8 rows x 17 columns]

In [13]:
if 'Private' in df.columns:
    df = pd.get_dummies(df, columns=['Private'], drop_first=True)
    print("One-hot encoding applied to 'Private' column.")
else:
    print("'Private' column not found, assuming it has already been encoded.")
df.head()

One-hot encoding applied to 'Private' column.

   Apps  Accept  Enroll  Top10perc  ...  perc.alumni  Expend  Grad.Rate  Private_Yes
0  1660    1232     721         23  ...           12    7041         60         True
1  2186    1924     512         16  ...           16   10527         56         True
2  1428    1097     336         22  ...           30    8735         54         True
3   417     349     137         60  ...           37   19016         59         True
4   193     146      55         16  ...            2   10922         15         True

[5 rows x 18 columns]

In [14]:
x = df.drop(columns=['Grad.Rate'])
y = df['Grad.Rate']

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [16]:
x_train.shape

(543, 17)

In [17]:
y_train.shape

(543,)

In [18]:
x_test.shape

(234, 17)

In [19]:
y_test.shape

(234,)

#Linear Regression Using scikit-learn

In [20]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [21]:
y_train_pred = lr.predict(x_train)
y_test_pred = lr.predict(x_test)

In [33]:
print(f"Intercept term: {lr.intercept_:.2f}")

Intercept term: 34.94

In [37]:
coefficients = pd.DataFrame({
    'feature': x_train.columns,
    'coefficient': lr.coef_
})

# Identify categorical features - in this case, only 'Private_Yes' after one-hot encoding
categorical_features = ['Private_Yes']

categorical_coefficients = coefficients[coefficients['feature'].isin(categorical_features)]
categorical_coefficients

if not categorical_coefficients.empty:
    highest_coeff_categorical = categorical_coefficients.loc[categorical_coefficients['coefficient'].abs().idxmax()]
    print(f"The categorical predictor with the highest coefficient is '{highest_coeff_categorical['feature']}' with a coefficient of {highest_coeff_categorical['coefficient']:.2f}.")
else:
    print("No categorical features found with coefficients.")

The categorical predictor with the highest coefficient is 'Private_Yes' with a coefficient of 5.05.

In [39]:
categorical_coefficients

        feature  coefficient
16  Private_Yes     5.050563

In [38]:
# Exclude categorical features
numerical_coefficients = coefficients[~coefficients['feature'].isin(categorical_features)]

if not numerical_coefficients.empty:
    highest_coeff_numerical = numerical_coefficients.loc[numerical_coefficients['coefficient'].abs().idxmax()]
    print(f"Excluding categorical predictors, the predictor with the highest coefficient is '{highest_coeff_numerical['feature']}' with a coefficient of {highest_coeff_numerical['coefficient']:.2f}.")
else:
    print("No numerical features found with coefficients.")

Excluding categorical predictors, the predictor with the highest coefficient is 'perc.alumni' with a coefficient of 0.34.

In [40]:
numerical_coefficients

        feature  coefficient
0          Apps     0.001524
1        Accept    -0.001380
2        Enroll     0.002042
3     Top10perc     0.033537
4     Top25perc     0.144385
5   F.Undergrad    -0.000183
6   P.Undergrad    -0.002003
7      Outstate     0.000704
8    Room.Board     0.002151
9         Books    -0.001921
10     Personal    -0.001835
11          PhD     0.141737
12     Terminal    -0.111153
13    S.F.Ratio    -0.028293
14  perc.alumni     0.337611
15       Expend    -0.000532

In [23]:
pd.DataFrame({'Actual Train': y_train, 'Predicted Train': np.round(y_train_pred, 2)}).sample(5, random_state=0) # Training data

     Actual Train  Predicted Train
153            51            69.08
718            72            81.03
1              56            62.05
122            91            86.07
318            81            76.39

In [24]:
pd.DataFrame({'Actual Test': y_test, 'Predicted Test': np.round(y_test_pred, 2)}).sample(5, random_state=0) #Testing data

     Actual Test  Predicted Test
108           52           73.53
65            49           64.52
300           75           54.35
135           76           60.31
290           61           53.00

In [30]:
def regression_metrics(y_train, y_train_pred, y_test, y_test_pred):
  def compute_metrics(y, y_pred):
    mse = mean_squared_error(y, y_pred)
    rsme = np.sqrt(mse)
    mae = mean_absolute_error(y, y_pred)
    mape = mean_absolute_percentage_error(y, y_pred) * 100
    r2 = r2_score(y, y_pred)
    var = y.var()
    std = y.std()
    mean_val = y.mean()

    return mse, var, rsme, std, mae, mean_val, mape, r2


  metrics_train = compute_metrics(y_train, y_train_pred)
  metrics_test = compute_metrics(y_test, y_test_pred)

  return pd.DataFrame({'Dataset': ['Training', 'Testing'], 'MSE': [metrics_train[0], metrics_test[0]],
                       'Variance': [metrics_train[1], metrics_test[1]],
                       'RMSE': [metrics_train[2], metrics_test[2]],
                       'St-Dev': [metrics_train[3], metrics_test[3]],
                       'MAE': [metrics_train[4], metrics_test[4]],
                       'Mean': [metrics_train[5], metrics_test[5]],
                       'MAPE': [metrics_train[6], metrics_test[6]],
                       'R2': [metrics_train[7], metrics_test[7]]}).set_index('Dataset')

In [32]:
df_metrics = regression_metrics(y_train, y_train_pred, y_test, y_test_pred).round(2)
df_metrics

             MSE  Variance   RMSE  St-Dev   MAE   Mean   MAPE    R2
Dataset
Training  160.59    299.49  12.67   17.31  9.37  65.20  17.28  0.46
Testing   160.48    285.52  12.67   16.90  9.60  66.08  18.04  0.44